---
title: Deadlines for masters modules 2017/18
output: html_document
---
```{r, include=F, echo=F}
library(readxl)
library(tidyverse)
library(lubridate)

CURRENT_YEAR = 2018
XMAS_START = dmy("15/12/18")
XMAS_END = dmy("06/01/19")
EASTER_START = dmy("06/04/19")
EASTER_END = dmy("28/04/19")

source('bizdays/bizdays.R')
```

```{r, include=F}
lastyear <- read_csv(paste0(CURRENT_YEAR-1, "/pg-deadlines.csv")) %>% 
  select(matches("module|element|markers"), deadline) %>% 
  mutate(deadline=lubridate::as_date(deadline))

exceptions <- read_csv(paste0(CURRENT_YEAR, '/EXCEPTIONS.csv')) %>% 
  mutate(deadline = dmy(deadline))

thisyear <- 
  lastyear %>% 
  rowwise() %>% 
  mutate(
    deadline = deadline + years(1),
    deadline = next_student_bizday(deadline),
    deadline = nearest_thursday(deadline)
  ) %>% 
  ungroup() %>% 
  left_join(., exceptions, by=c("module.code", 'element.title')) %>% 
  mutate(deadline = as_date(ifelse(!is.na(deadline.y), deadline.y, deadline.x))) %>% 
  select(-matches("deadline.x|deadline.y")) %>% 
  glimpse %>% 
  # now add extras for return etc
  rowwise() %>%
  mutate(
    deadline.self.cert.ec = next_student_bizday(deadline + days(5)),
    deadline.ec = next_student_bizday(deadline + days(10)),
    return.internal = next_staff_bizday(deadline + weeks(3)),
    return.hard = next_staff_bizday(deadline + weeks(4)),
    return.ec = next_staff_bizday(deadline.ec + weeks(4))
  ) %>% 
  ungroup() 



# Write out the data

write_excel_csv(thisyear, paste0(CURRENT_YEAR, "/pg-deadlines.csv"))

student.version <- 
  thisyear %>% 
  arrange(deadline) %>% 
  select(module.code, element.title, module.leader, deadline, deadline.self.cert.ec, deadline.ec, return.hard) %>% 
  rename(return = return.hard, assignment=element.title) %>% 
  mutate_each(funs(pdate), contains("deadline"), contains("return")) 

write.csv(student.version, paste0(CURRENT_YEAR, '/student_version.csv'))
```



